### ISSUE TITLE
remove config.cson from tasks

### ISSUE THREAD

**Issue by gperdomor** [danbohea/ansible-role-atom#1]
Please remove `config.cson` file copy from the main workflow. Atom should generate the default config when start the first time

**Comment by dixhuit** [comment]
Good spot. The role is still copying a very old version of my own personal config.cson. I'll remove it initially but ultimately I think we should have a configurable option for importing config.cson and specifying the source file to copy.

**Comment by dixhuit** [comment]
All fixed. Have also added a new var `atom_config_src_path` so that we can still use this role to import config.cson. I've also tagged a 1.0.0 release.
